name: publish
on: workflow_dispatch
permissions:
  id-token: write
  contents: read
jobs:
  call:
    uses: ./.github/workflows/reusable-pub.yml
    permissions:
      id-token: write
      contents: read
